// apps/angular-playground/pinned-rows-demo.component.ts
import { Component, computed, signal } from "@angular/core";
import {
  AwbGrid,
  ColumnType,
  type NgColDef,
  type RowClassParams,
} from "@agility-workbench/angular-grid";

type Row = {
  id: string;
  team: string;
  owner: string;
  pipeline: number;
  closed: number;
};

const ROWS: Row[] = Array.from({ length: 80 }, (_, index) => ({
  id: `deal-${index + 1}`,
  team: ["Enterprise", "Commercial", "Growth"][index % 3],
  owner: ["Ava", "Liam", "Mia", "Noah", "Emma"][index % 5],
  pipeline: 25_000 + ((index * 7_919) % 180_000),
  closed: 8_000 + ((index * 3_571) % 95_000),
}));

@Component({
  selector: "pinned-rows-demo",
  standalone: true,
  imports: [AwbGrid],
  template: `
    <div style="display: flex; align-items: center; gap: 8px; flex-wrap: wrap">
      <button class="btn" type="button" (click)="showTarget.set(!showTarget())">
        {{ showTarget() ? "Hide" : "Show" }} top forecast
      </button>
      <button class="btn" type="button" (click)="showTotals.set(!showTotals())">
        {{ showTotals() ? "Hide" : "Show" }} bottom totals
      </button>
      <button class="btn" type="button" (click)="raiseForecast()">Raise forecast</button>
      <span style="font-size: 12px; color: #6b7280">
        Pinned rows stay outside sort, filter, pagination, and the virtualized row count.
        Right-click any data row for Pin row / Unpin row.
      </span>
    </div>
    <div style="flex: 1; min-height: 0">
      <awb-grid
        [rowData]="rows"
        [columnDefs]="columns"
        rowIdKey="id"
        [pinnedRowsEditable]="true"
        [rowPinningMenu]="true"
        [pinnedTopRowData]="topRows()"
        [pinnedBottomRowData]="bottomRows()"
        [quickFilter]="{ mode: 'always', debounceMs: 0 }"
        [toolbar]="{ sorting: true }"
        [getRowClass]="rowClass"
      />
    </div>
  `,
  styles: [":host { display: flex; flex-direction: column; height: 100%; gap: 10px; min-height: 0 }"],
})
export class PinnedRowsDemoComponent {
  readonly rows = ROWS;
  readonly showTarget = signal(true);
  readonly showTotals = signal(true);
  readonly forecast = signal(8_500_000);

  readonly columns: NgColDef[] = [
    { colId: "team", key: "team", label: "Team", width: 150, pinned: "left" },
    { colId: "owner", key: "owner", label: "Owner", width: 140, editable: true },
    {
      colId: "pipeline",
      key: "pipeline",
      label: "Pipeline",
      width: 160,
      type: ColumnType.CURRENCY,
    },
    {
      colId: "closed",
      key: "closed",
      label: "Closed",
      width: 160,
      type: ColumnType.CURRENCY,
    },
  ];

  private readonly totalPipeline = ROWS.reduce((sum, row) => sum + row.pipeline, 0);
  private readonly totalClosed = ROWS.reduce((sum, row) => sum + row.closed, 0);

  readonly topRows = computed<Row[]>(() => this.showTarget() ? [{
    id: "forecast",
    team: "FY forecast",
    owner: "All teams",
    pipeline: this.forecast(),
    closed: 6_400_000,
  }] : []);

  readonly bottomRows = computed<Row[]>(() => this.showTotals() ? [{
    id: "totals",
    team: "Visible dataset",
    owner: `${ROWS.length} deals`,
    pipeline: this.totalPipeline,
    closed: this.totalClosed,
  }] : []);

  readonly rowClass = ({ node }: RowClassParams): string | undefined =>
    node.rowPinned ? `demo-pinned-${node.rowPinned}` : undefined;

  raiseForecast(): void {
    this.forecast.set(this.forecast() + 250_000);
  }
}

// apps/react-playground/PinnedRowsDemo.tsx
import { useMemo, useState } from "react";

import { Grid, ColumnType, type ReactColDef } from "@react-grid";

type Row = {
  id: string;
  team: string;
  owner: string;
  pipeline: number;
  closed: number;
};

const ROWS: Row[] = Array.from({ length: 80 }, (_, index) => ({
  id: `deal-${index + 1}`,
  region: ["AMER", "APAC", "OCEANIC"][index % 3],
  team: ["Enterprise", "Commercial", "Growth"][index % 3],
  country: ["USA", "Canada", "Brazil", "India", "France", "Denmark", "China", "Japan", "Australia", "Spain"][index % 10],
  owner: ["Ava", "Liam", "Mia", "Noah", "Emma", "Kent", "Duke", "Frank", "Will", "Smith", "Leo", "Brad", "Oliver", "Nick", "Romeo"][index % 15],
  pipeline: 25_000 + ((index * 7_919) % 180_000),
  closed: 8_000 + ((index * 3_571) % 95_000),
}));

export function PinnedRowsDemo() {
  const [showTarget, setShowTarget] = useState(true);
  const [showTotals, setShowTotals] = useState(true);
  const [forecast, setForecast] = useState(8_500_000);

  const columns = useMemo<ReactColDef[]>(() => [
    { colId: "team", key: "team", label: "Team", width: 150, pinned: "left" },
    { colId: "region", key: "region", label: "Region", width: 150 },
    { colId: "country", key: "country", label: "Country", width: 150 },
    { colId: "owner", key: "owner", label: "Owner", width: 140, editable: true },
    {
      colId: "pipeline",
      key: "pipeline",
      label: "Pipeline",
      width: 160,
      type: ColumnType.CURRENCY,
    },
    {
      colId: "closed",
      key: "closed",
      label: "Closed",
      width: 160,
      type: ColumnType.CURRENCY,
    },
  ], []);

  const totalPipeline = ROWS.reduce((sum, row) => sum + row.pipeline, 0);
  const totalClosed = ROWS.reduce((sum, row) => sum + row.closed, 0);
  const topRows: Row[] = showTarget ? [{
    id: "forecast",
    team: "FY forecast",
    owner: "All teams",
    pipeline: forecast,
    closed: 6_400_000,
  }] : [];
  const bottomRows: Row[] = showTotals ? [{
    id: "totals",
    team: "Visible dataset",
    owner: `${ROWS.length} deals`,
    pipeline: totalPipeline,
    closed: totalClosed,
  }] : [];

  return (
    <div style={{ height: "100%", display: "flex", flexDirection: "column", gap: 10 }}>
      <div style={{ display: "flex", alignItems: "center", gap: 8, flexWrap: "wrap" }}>
        <button className="btn" type="button" onClick={() => setShowTarget(value => !value)}>
          {showTarget ? "Hide" : "Show"} top forecast
        </button>
        <button className="btn" type="button" onClick={() => setShowTotals(value => !value)}>
          {showTotals ? "Hide" : "Show"} bottom totals
        </button>
        <button className="btn" type="button" onClick={() => setForecast(value => value + 250_000)}>
          Raise forecast
        </button>
        <span style={{ fontSize: 12, color: "#6b7280" }}>
          Pinned rows stay outside sort, filter, pagination, and the virtualized row count.
          Right-click any data row for Pin row / Unpin row.
        </span>
      </div>
      <div style={{ flex: 1, minHeight: 0 }}>
        <Grid
          rowData={ROWS}
          columnDefs={columns}
          rowIdKey="id"
          pinnedRowsEditable
          rowPinningMenu
          pinnedTopRowData={topRows}
          pinnedBottomRowData={bottomRows}
          quickFilter={{ mode: "always", debounceMs: 0 }}
          toolbar={{ sorting: true }}
          getRowClass={({ node }) => node.rowPinned ? `demo-pinned-${node.rowPinned}` : undefined}
          style={{ width: "100%", height: "100%" }}
        />
      </div>
    </div>
  );
}

export default PinnedRowsDemo;
