// apps/playground/VisualStatesDemo.tsx
import { useMemo, useState } from "react";

import { Grid } from "@react-grid";
import type { ReactColDef } from "@react-grid";
import { ColumnType } from "@grid/interfaces/column";
import { themeLight, themeDark } from "@grid";
import type { GridTheme } from "@grid";

/**
 * Playground for the row/cell visual-state and interaction options:
 *   Visual:      rowHover, columnHover, zebraRows, highlightActiveCell
 *   Interaction: cellSelection (true/false/text), rangeSelection, columnSelection, bodyContextMenu
 *   Header:      showColumnButtonsOnHover (grid-level), plus per-column showColumnMenu /
 *                columnContextMenu demonstrated on the Rating and City columns
 *
 * Toggle each independently, in light or dark, and optionally apply custom colors through the
 * semantic theme params (activeCellBorderColor / rowAltBackgroundColor / columnHoverColor) to
 * confirm they feed the same CSS variables. The Name column is editable, so the body context menu
 * gains Cut / Paste when a Name cell is in the selection.
 */

type PersonRow = {
  id: number;
  name: string;
  department: string;
  city: string;
  salary: number;
  rating: number;
  active: string;
};

const FIRST = ["Ava", "Liam", "Mia", "Noah", "Emma", "Ethan", "Olivia", "Lucas", "Sophia", "Mason", "Isla", "Leo"];
const LAST = ["Chen", "Patel", "Kim", "Garcia", "Nguyen", "Silva", "Khan", "Rossi", "Haas", "Ito", "Novak", "Park"];
const DEPTS = ["Engineering", "Sales", "Marketing", "Finance", "Operations", "Support"];
const CITIES = ["New York", "Chicago", "Seattle", "Austin", "Denver", "Miami", "Boston", "Portland"];

// Deterministic PRNG so the demo data is stable across reloads.
function mulberry32(seed: number) {
  return () => {
    seed |= 0;
    seed = (seed + 0x6d2b79f5) | 0;
    let t = Math.imul(seed ^ (seed >>> 15), 1 | seed);
    t = (t + Math.imul(t ^ (t >>> 7), 61 | t)) ^ t;
    return ((t ^ (t >>> 14)) >>> 0) / 4294967296;
  };
}

function buildRows(count: number): PersonRow[] {
  const rand = mulberry32(7);
  const pick = <T,>(arr: T[]) => arr[Math.floor(rand() * arr.length)];
  return Array.from({ length: count }, (_, i) => ({
    id: 1000 + i,
    name: `${pick(FIRST)} ${pick(LAST)}`,
    department: pick(DEPTS),
    city: pick(CITIES),
    salary: 60_000 + Math.floor(rand() * 140_000),
    rating: +(1 + rand() * 4).toFixed(1),
    active: rand() > 0.25 ? "Yes" : "No",
  }));
}

const themePresets = [
  { id: "light", label: "Light", className: "pte-theme-light" },
  { id: "dark", label: "Dark", className: "pte-theme-dark" },
];

// Custom accent colors layered on top of a preset via the semantic theme params added for these
// features. Each fans out to its --pte-* variable.
const CUSTOM_PARAMS = {
  activeCellBorderColor: "#f97316", // orange active-cell outline
  rowAltBackgroundColor: "#fff7ed", // warm zebra stripe (light)
  columnHoverColor: "#ffedd5", // warm column hover (light)
};
const CUSTOM_PARAMS_DARK = {
  activeCellBorderColor: "#fb923c",
  rowAltBackgroundColor: "#20160c",
  columnHoverColor: "#2a1c0e",
};

function Toggle({ label, checked, onChange, hint }: {
  label: string;
  checked: boolean;
  onChange: (v: boolean) => void;
  hint?: string;
}) {
  return (
    <label style={{ display: "flex", alignItems: "center", gap: 6, fontSize: 13, cursor: "pointer" }} title={hint}>
      <input type="checkbox" checked={checked} onChange={(e) => onChange(e.target.checked)} />
      {label}
    </label>
  );
}

export function VisualStatesDemo() {
  const rows = useMemo(() => buildRows(200), []);

  const [rowHover, setRowHover] = useState(true);
  const [columnHover, setColumnHover] = useState(true);
  const [zebraRows, setZebraRows] = useState(true);
  const [highlightActiveCell, setHighlightActiveCell] = useState(true);

  // Interaction gating (defaults preserve today's behavior).
  const [cellSelection, setCellSelection] = useState<"true" | "false" | "text">("true");
  const [rangeSelection, setRangeSelection] = useState(true);
  const [columnSelection, setColumnSelection] = useState(true);
  const [bodyMenu, setBodyMenu] = useState<"default" | "native" | "custom" | "empty">("default");
  const [editTrigger, setEditTrigger] = useState<"doubleClick" | "singleClick" | "none">("doubleClick");
  const [suppressKeyboardEdit, setSuppressKeyboardEdit] = useState(false);
  const [suppressTypeToEdit, setSuppressTypeToEdit] = useState(false);
  const [moveAfterEdit, setMoveAfterEdit] = useState(true);
  const [commitOnBlur, setCommitOnBlur] = useState(true);

  // Conditional styling (getRowStyle + per-column cellStyle/cellClass).
  const [conditionalStyling, setConditionalStyling] = useState(true);

  // Sort config: an initial sort (Salary desc) + a custom Department comparator (by a fixed order).
  // NOTE: initial sort seeds ONCE at first column setup, so toggling it needs a grid remount (key).
  const [sortConfig, setSortConfig] = useState(true);

  // Event-callback readout: shows the most recent grid event (onCellClicked / onSortChanged / …).
  const [lastEvent, setLastEvent] = useState<string>("—");

  // Header / column-menu options.
  const [buttonsOnHover, setButtonsOnHover] = useState(false);
  // Per-column flags demonstrated on specific columns: hide the menu (⋮) button on "Rating", and
  // disable the right-click column menu on "City" (its header falls back to the native menu).
  const [hideRatingMenu, setHideRatingMenu] = useState(true);
  const [nativeCityMenu, setNativeCityMenu] = useState(true);

  // Map the string control to the option's boolean | "text" value.
  const cellSelectionValue: boolean | "text" =
    cellSelection === "text" ? "text" : cellSelection === "true";

  // Map the body-menu control onto bodyContextMenu's boolean | getter shape.
  const bodyContextMenu = useMemo(() => {
    switch (bodyMenu) {
      case "native": return false;                                    // browser's native menu
      case "empty": return () => [];                                  // grid owns it, shows nothing
      case "custom":                                                  // defaults + a custom item
        return ({ items }: { items: any[] }) => [
          ...items,
          { isSeparator: true },
          { id: "hello", label: "Say hello", onClick: () => window.alert("Hello from a custom item!") },
        ];
      default: return true;                                           // default grid menu
    }
  }, [bodyMenu]);

  const [themeId, setThemeId] = useState(themePresets[0].id);
  const [customColors, setCustomColors] = useState(false);

  const activePreset = themePresets.find((t) => t.id === themeId) ?? themePresets[0];

  const theme = useMemo<GridTheme | undefined>(() => {
    if (!customColors) return undefined;
    const base = themeId === "dark" ? themeDark : themeLight;
    return base.withParams(themeId === "dark" ? CUSTOM_PARAMS_DARK : CUSTOM_PARAMS);
  }, [customColors, themeId]);

  // getRowStyle: subtly dim inactive employees (active === "No").
  const getRowStyle = conditionalStyling
    ? (p: { data: PersonRow }) => (p.data.active === "No" ? { opacity: "0.55" } : undefined)
    : undefined;

  const columnDefs = useMemo<ReactColDef[]>(() => [
    { colId: "id", key: "id", label: "ID", width: 80 },
    // Editable → the body context menu gains Cut / Paste (right-click a Name cell).
    { colId: "name", key: "name", label: "Name", width: 160, editable: true, filter: true },
    {
      colId: "department", key: "department", label: "Department", width: 140, filter: true,
      // Custom comparator: sort by a fixed department priority rather than alphabetically.
      comparator: sortConfig
        ? (a: string, b: string) => DEPTS.indexOf(a) - DEPTS.indexOf(b)
        : undefined,
    },
    // columnContextMenu: false → right-clicking this header shows the browser's native menu.
    { colId: "city", key: "city", label: "City", width: 130, filter: true, columnContextMenu: !nativeCityMenu },
    {
      colId: "salary", key: "salary", label: "Salary", width: 120, type: ColumnType.NUMBER,
      // Initial sort: Salary descending on first load.
      sort: sortConfig ? "desc" : undefined,
      // cellStyle: color high salaries green, low ones muted (function of the cell value).
      cellStyle: conditionalStyling
        ? (p: { value: number }) => ({ color: p.value >= 150_000 ? "#16a34a" : "#9ca3af", fontWeight: p.value >= 150_000 ? "600" : "400" })
        : undefined,
    },
    // showColumnMenu: false → the ⋮ button is hidden on this header (menu still via right-click).
    { colId: "rating", key: "rating", label: "Rating", width: 100, type: ColumnType.NUMBER, showColumnMenu: !hideRatingMenu },
    { colId: "active", key: "active", label: "Active", width: 90 },
  ], [hideRatingMenu, nativeCityMenu, conditionalStyling, sortConfig]);

  return (
    <div style={{ display: "flex", flexDirection: "column", gap: 12, height: "100%" }}>
      <div style={{ display: "flex", alignItems: "center", gap: 20, flexWrap: "wrap" }}>
        <div style={{ display: "flex", alignItems: "center", gap: 14, padding: "6px 12px", border: "1px solid var(--pte-frame-border-color, #ccc)", borderRadius: 8 }}>
          <strong style={{ fontSize: 12, textTransform: "uppercase", letterSpacing: 0.4, color: "#6b7280" }}>Visual</strong>
          <Toggle label="rowHover" checked={rowHover} onChange={setRowHover} hint="Highlight the row under the pointer" />
          <Toggle label="columnHover" checked={columnHover} onChange={setColumnHover} hint="Highlight the whole column under the pointer" />
          <Toggle label="zebraRows" checked={zebraRows} onChange={setZebraRows} hint="Alternating background on odd rows" />
          <Toggle label="highlightActiveCell" checked={highlightActiveCell} onChange={setHighlightActiveCell} hint="Outline the focused cell inside a range" />
          <Toggle label="conditionalStyling" checked={conditionalStyling} onChange={setConditionalStyling} hint="getRowStyle dims inactive rows; the Salary column's cellStyle colors high/low values" />
          <Toggle label="sortConfig" checked={sortConfig} onChange={setSortConfig} hint="Initial sort (Salary desc) + custom Department comparator (fixed priority order). Applied on load." />
        </div>

        <div style={{ display: "flex", alignItems: "center", gap: 14, padding: "6px 12px", border: "1px solid var(--pte-frame-border-color, #ccc)", borderRadius: 8 }}>
          <strong style={{ fontSize: 12, textTransform: "uppercase", letterSpacing: 0.4, color: "#6b7280" }}>Interaction</strong>
          <label style={{ display: "flex", alignItems: "center", gap: 6, fontSize: 13 }}
            title="true = grid cell selection · false = inert cells · text = native browser text selection (like a plain HTML table)">
            cellSelection
            <select value={cellSelection} onChange={(e) => setCellSelection(e.target.value as typeof cellSelection)}>
              <option value="true">true (grid)</option>
              <option value="false">false (inert)</option>
              <option value="text">text (native)</option>
            </select>
          </label>
          <Toggle label="rangeSelection" checked={rangeSelection} onChange={setRangeSelection} hint="Allow drag / Shift+Arrow to extend a multi-cell range" />
          <Toggle label="columnSelection" checked={columnSelection} onChange={setColumnSelection} hint="Allow clicking a column header to select the column" />
          <label style={{ display: "flex", alignItems: "center", gap: 6, fontSize: 13 }}
            title="How a mouse gesture starts editing the (editable) Name column. Keyboard triggers are governed by suppressKeyboardEdit.">
            editTrigger
            <select value={editTrigger} onChange={(e) => setEditTrigger(e.target.value as typeof editTrigger)}>
              <option value="doubleClick">doubleClick</option>
              <option value="singleClick">singleClick</option>
              <option value="none">none</option>
            </select>
          </label>
          <Toggle label="suppressKeyboardEdit" checked={suppressKeyboardEdit} onChange={setSuppressKeyboardEdit} hint="Disable F2 / Enter / type-to-edit (mouse trigger unaffected)" />
          <Toggle label="suppressTypeToEdit" checked={suppressTypeToEdit} onChange={setSuppressTypeToEdit} hint="Disable only type-to-edit; F2 / Enter still start editing" />
          <Toggle label="moveAfterEdit" checked={moveAfterEdit} onChange={setMoveAfterEdit} hint="After committing, Enter moves down / Tab moves right (edit the Name column to try)" />
          <Toggle label="commitOnBlur" checked={commitOnBlur} onChange={setCommitOnBlur} hint="Commit the editor when it loses focus; off keeps it open" />
          <label style={{ display: "flex", alignItems: "center", gap: 6, fontSize: 13 }}
            title="default = grid menu · native = browser menu · custom = grid menu + a custom item · empty = no menu (native suppressed)">
            bodyContextMenu
            <select value={bodyMenu} onChange={(e) => setBodyMenu(e.target.value as typeof bodyMenu)}>
              <option value="default">default</option>
              <option value="native">false (native)</option>
              <option value="custom">custom items</option>
              <option value="empty">[] (none)</option>
            </select>
          </label>
        </div>

        <div style={{ display: "flex", alignItems: "center", gap: 14, padding: "6px 12px", border: "1px solid var(--pte-frame-border-color, #ccc)", borderRadius: 8 }}>
          <strong style={{ fontSize: 12, textTransform: "uppercase", letterSpacing: 0.4, color: "#6b7280" }}>Header</strong>
          <Toggle label="showColumnButtonsOnHover" checked={buttonsOnHover} onChange={setButtonsOnHover} hint="Reveal the header menu / filter buttons only on header hover or focus (grid-level)" />
          <Toggle label="Rating: showColumnMenu=false" checked={hideRatingMenu} onChange={setHideRatingMenu} hint="Hide the ⋮ menu button on the Rating column (menu still reachable via right-click)" />
          <Toggle label="City: columnContextMenu=false" checked={nativeCityMenu} onChange={setNativeCityMenu} hint="Right-clicking the City header shows the browser's native menu instead of the grid column menu" />
        </div>

        <div style={{ display: "flex", alignItems: "center", gap: 8 }}>
          <label htmlFor="vs-theme" style={{ fontSize: 13 }}>Theme</label>
          <select id="vs-theme" value={themeId} onChange={(e) => setThemeId(e.target.value)}>
            {themePresets.map((t) => <option key={t.id} value={t.id}>{t.label}</option>)}
          </select>
          <Toggle label="Custom colors" checked={customColors} onChange={setCustomColors} hint="Apply the new semantic theme params (orange accent)" />
        </div>
      </div>

      <p style={{ fontSize: 12, color: "#6b7280", margin: 0 }}>
        Hover rows and columns to see the highlights. Click a cell, then Shift+Click (or Shift+Arrow) to
        make a range — with <code>highlightActiveCell</code> on, the focused cell keeps a distinct outline
        inside the selection. Use the <strong>Interaction</strong> controls to disable range dragging or
        column-header selection, or set <code>cellSelection</code> to <code>text</code> to revert to a plain
        HTML table where you can drag to select and copy cell text. Right-click the body to try the
        <code>bodyContextMenu</code> modes (default / native / custom items / none) — with a Name cell
        selected the menu also shows Cut / Paste (Name is editable). Under <strong>Header</strong>, turn on
        <code>showColumnButtonsOnHover</code> and hover a header to reveal its ⋮ / filter buttons; the
        Rating column hides its ⋮ button and the City header opens the browser's native menu on
        right-click. Toggle <code>Custom colors</code> to recolor these states via theme params.
      </p>

      <div style={{ flex: 1, minHeight: 0 }} className={activePreset.className}>
        {/* Runtime options update the existing grid instance so selection and scroll state survive. */}
        <Grid
          // cellSelection: "true" | "false" | "text" mapped to boolean | "text"
          data={rows}
          columnDefs={columnDefs}
          rowIdKey="id"
          rowHover={rowHover}
          columnHover={columnHover}
          zebraRows={zebraRows}
          highlightActiveCell={highlightActiveCell}
          getRowStyle={getRowStyle}
          onCellClicked={(p) => setLastEvent(`onCellClicked → row ${p.rowId}, col "${p.colId}" = ${JSON.stringify(p.value)}`)}
          onSortChanged={() => setLastEvent("onSortChanged")}
          onSelectionChanged={(p) => setLastEvent(`onSelectionChanged → ${p.snapshot.kind}`)}
          onCellValueChanged={(p) => setLastEvent(`onCellValueChanged → row ${p.rowId}, col "${p.colId}" = ${JSON.stringify(p.value)}`)}
          cellSelection={cellSelectionValue}
          rangeSelection={rangeSelection}
          columnSelection={columnSelection}
          editTrigger={editTrigger}
          suppressKeyboardEdit={suppressKeyboardEdit}
          suppressTypeToEdit={suppressTypeToEdit}
          moveAfterEdit={moveAfterEdit}
          commitOnBlur={commitOnBlur}
          bodyContextMenu={bodyContextMenu}
          showColumnButtonsOnHover={buttonsOnHover}
          theme={theme}
          style={{ width: "100%", height: "100%" }}
        />
      </div>

      <div style={{ fontSize: 12, color: "#6b7280", fontFamily: "monospace" }}>
        Last event: <span style={{ color: "var(--pte-text-color, #111)" }}>{lastEvent}</span>
      </div>
    </div>
  );
}

export default VisualStatesDemo;

// apps/angular-playground/visual-states-demo.component.ts
import { Component, computed, input, output, signal } from "@angular/core";
import {
  AwbGrid,
  ColumnType,
  themeLight,
  themeDark,
  type BodyMenuContext,
  type CellValueChangedParams,
  type GridEventCellClickedParams,
  type GridEventSelectionChangedParams,
  type GridTheme,
  type NgColDef,
  type NgMenuItem,
  type RowClassParams,
} from "@agility-workbench/angular-grid";

/**
 * Playground for the row/cell visual-state and interaction options:
 *   Visual:      rowHover, columnHover, zebraRows, highlightActiveCell
 *   Interaction: cellSelection (true/false/text), rangeSelection, columnSelection, bodyContextMenu
 *   Header:      showColumnButtonsOnHover (grid-level), plus per-column showColumnMenu /
 *                columnContextMenu demonstrated on the Rating and City columns
 *
 * Toggle each independently, in light or dark, and optionally apply custom colors through the
 * semantic theme params (activeCellBorderColor / rowAltBackgroundColor / columnHoverColor) to
 * confirm they feed the same CSS variables. The Name column is editable, so the body context menu
 * gains Cut / Paste when a Name cell is in the selection.
 */

type PersonRow = {
  id: number;
  name: string;
  department: string;
  city: string;
  salary: number;
  rating: number;
  active: string;
};

const FIRST = ["Ava", "Liam", "Mia", "Noah", "Emma", "Ethan", "Olivia", "Lucas", "Sophia", "Mason", "Isla", "Leo"];
const LAST = ["Chen", "Patel", "Kim", "Garcia", "Nguyen", "Silva", "Khan", "Rossi", "Haas", "Ito", "Novak", "Park"];
const DEPTS = ["Engineering", "Sales", "Marketing", "Finance", "Operations", "Support"];
const CITIES = ["New York", "Chicago", "Seattle", "Austin", "Denver", "Miami", "Boston", "Portland"];

// Deterministic PRNG so the demo data is stable across reloads.
function mulberry32(seed: number) {
  return () => {
    seed |= 0;
    seed = (seed + 0x6d2b79f5) | 0;
    let t = Math.imul(seed ^ (seed >>> 15), 1 | seed);
    t = (t + Math.imul(t ^ (t >>> 7), 61 | t)) ^ t;
    return ((t ^ (t >>> 14)) >>> 0) / 4294967296;
  };
}

function buildRows(count: number): PersonRow[] {
  const rand = mulberry32(7);
  const pick = <T,>(arr: T[]) => arr[Math.floor(rand() * arr.length)];
  return Array.from({ length: count }, (_, i) => ({
    id: 1000 + i,
    name: `${pick(FIRST)} ${pick(LAST)}`,
    department: pick(DEPTS),
    city: pick(CITIES),
    salary: 60_000 + Math.floor(rand() * 140_000),
    rating: +(1 + rand() * 4).toFixed(1),
    active: rand() > 0.25 ? "Yes" : "No",
  }));
}

const themePresets = [
  { id: "light", label: "Light", className: "pte-theme-light" },
  { id: "dark", label: "Dark", className: "pte-theme-dark" },
];

// Custom accent colors layered on top of a preset via the semantic theme params added for these
// features. Each fans out to its --pte-* variable.
const CUSTOM_PARAMS = {
  activeCellBorderColor: "#f97316", // orange active-cell outline
  rowAltBackgroundColor: "#fff7ed", // warm zebra stripe (light)
  columnHoverColor: "#ffedd5", // warm column hover (light)
};
const CUSTOM_PARAMS_DARK = {
  activeCellBorderColor: "#fb923c",
  rowAltBackgroundColor: "#20160c",
  columnHoverColor: "#2a1c0e",
};

/** Checkbox toggle helper, used only by this demo. */
@Component({
  selector: "vs-toggle",
  standalone: true,
  template: `
    <label
      style="display: flex; align-items: center; gap: 6px; font-size: 13px; cursor: pointer"
      [title]="hint() ?? ''"
    >
      <input type="checkbox" [checked]="checked()" (change)="toggled.emit($any($event.target).checked)" />
      {{ label() }}
    </label>
  `,
})
export class VsToggleComponent {
  readonly label = input.required<string>();
  readonly checked = input.required<boolean>();
  readonly hint = input<string>();
  readonly toggled = output<boolean>();
}

@Component({
  selector: "visual-states-demo",
  standalone: true,
  imports: [AwbGrid, VsToggleComponent],
  template: `
    <div class="vs-controls">
      <div class="vs-group">
        <strong class="vs-group-title">Visual</strong>
        <vs-toggle label="rowHover" [checked]="rowHover()" (toggled)="rowHover.set($event)" hint="Highlight the row under the pointer" />
        <vs-toggle label="columnHover" [checked]="columnHover()" (toggled)="columnHover.set($event)" hint="Highlight the whole column under the pointer" />
        <vs-toggle label="zebraRows" [checked]="zebraRows()" (toggled)="zebraRows.set($event)" hint="Alternating background on odd rows" />
        <vs-toggle label="highlightActiveCell" [checked]="highlightActiveCell()" (toggled)="highlightActiveCell.set($event)" hint="Outline the focused cell inside a range" />
        <vs-toggle label="conditionalStyling" [checked]="conditionalStyling()" (toggled)="conditionalStyling.set($event)" hint="getRowStyle dims inactive rows; the Salary column's cellStyle colors high/low values" />
        <vs-toggle label="sortConfig" [checked]="sortConfig()" (toggled)="sortConfig.set($event)" hint="Initial sort (Salary desc) + custom Department comparator (fixed priority order). Applied on load." />
      </div>

      <div class="vs-group">
        <strong class="vs-group-title">Interaction</strong>
        <label class="vs-select"
          title="true = grid cell selection · false = inert cells · text = native browser text selection (like a plain HTML table)">
          cellSelection
          <select [value]="cellSelection()" (change)="setCellSelection($event)">
            <option value="true">true (grid)</option>
            <option value="false">false (inert)</option>
            <option value="text">text (native)</option>
          </select>
        </label>
        <vs-toggle label="rangeSelection" [checked]="rangeSelection()" (toggled)="rangeSelection.set($event)" hint="Allow drag / Shift+Arrow to extend a multi-cell range" />
        <vs-toggle label="columnSelection" [checked]="columnSelection()" (toggled)="columnSelection.set($event)" hint="Allow clicking a column header to select the column" />
        <label class="vs-select"
          title="How a mouse gesture starts editing the (editable) Name column. Keyboard triggers are governed by suppressKeyboardEdit.">
          editTrigger
          <select [value]="editTrigger()" (change)="setEditTrigger($event)">
            <option value="doubleClick">doubleClick</option>
            <option value="singleClick">singleClick</option>
            <option value="none">none</option>
          </select>
        </label>
        <vs-toggle label="suppressKeyboardEdit" [checked]="suppressKeyboardEdit()" (toggled)="suppressKeyboardEdit.set($event)" hint="Disable F2 / Enter / type-to-edit (mouse trigger unaffected)" />
        <vs-toggle label="suppressTypeToEdit" [checked]="suppressTypeToEdit()" (toggled)="suppressTypeToEdit.set($event)" hint="Disable only type-to-edit; F2 / Enter still start editing" />
        <vs-toggle label="moveAfterEdit" [checked]="moveAfterEdit()" (toggled)="moveAfterEdit.set($event)" hint="After committing, Enter moves down / Tab moves right (edit the Name column to try)" />
        <vs-toggle label="commitOnBlur" [checked]="commitOnBlur()" (toggled)="commitOnBlur.set($event)" hint="Commit the editor when it loses focus; off keeps it open" />
        <label class="vs-select"
          title="default = grid menu · native = browser menu · custom = grid menu + a custom item · empty = no menu (native suppressed)">
          bodyContextMenu
          <select [value]="bodyMenu()" (change)="setBodyMenu($event)">
            <option value="default">default</option>
            <option value="native">false (native)</option>
            <option value="custom">custom items</option>
            <option value="empty">[] (none)</option>
          </select>
        </label>
      </div>

      <div class="vs-group">
        <strong class="vs-group-title">Header</strong>
        <vs-toggle label="showColumnButtonsOnHover" [checked]="buttonsOnHover()" (toggled)="buttonsOnHover.set($event)" hint="Reveal the header menu / filter buttons only on header hover or focus (grid-level)" />
        <vs-toggle label="Rating: showColumnMenu=false" [checked]="hideRatingMenu()" (toggled)="hideRatingMenu.set($event)" hint="Hide the ⋮ menu button on the Rating column (menu still reachable via right-click)" />
        <vs-toggle label="City: columnContextMenu=false" [checked]="nativeCityMenu()" (toggled)="nativeCityMenu.set($event)" hint="Right-clicking the City header shows the browser's native menu instead of the grid column menu" />
      </div>

      <div class="vs-theme-picker">
        <label for="vs-theme" style="font-size: 13px">Theme</label>
        <select id="vs-theme" [value]="themeId()" (change)="setThemeId($event)">
          @for (t of themePresets; track t.id) {
            <option [value]="t.id">{{ t.label }}</option>
          }
        </select>
        <vs-toggle label="Custom colors" [checked]="customColors()" (toggled)="customColors.set($event)" hint="Apply the new semantic theme params (orange accent)" />
      </div>
    </div>

    <p class="vs-blurb">
      Hover rows and columns to see the highlights. Click a cell, then Shift+Click (or Shift+Arrow) to
      make a range — with <code>highlightActiveCell</code> on, the focused cell keeps a distinct outline
      inside the selection. Use the <strong>Interaction</strong> controls to disable range dragging or
      column-header selection, or set <code>cellSelection</code> to <code>text</code> to revert to a plain
      HTML table where you can drag to select and copy cell text. Right-click the body to try the
      <code>bodyContextMenu</code> modes (default / native / custom items / none) — with a Name cell
      selected the menu also shows Cut / Paste (Name is editable). Under <strong>Header</strong>, turn on
      <code>showColumnButtonsOnHover</code> and hover a header to reveal its ⋮ / filter buttons; the
      Rating column hides its ⋮ button and the City header opens the browser's native menu on
      right-click. Toggle <code>Custom colors</code> to recolor these states via theme params.
    </p>

    <!-- Runtime options update the existing grid instance so selection and scroll state survive. -->
    <div
      class="demo-grid-host"
      [class.pte-theme-light]="activePreset().id === 'light'"
      [class.pte-theme-dark]="activePreset().id === 'dark'"
    >
      <awb-grid
        [rowData]="rows"
        [columnDefs]="columnDefs()"
        rowIdKey="id"
        [rowHover]="rowHover()"
        [columnHover]="columnHover()"
        [zebraRows]="zebraRows()"
        [highlightActiveCell]="highlightActiveCell()"
        [getRowStyle]="getRowStyle()"
        (cellClicked)="onCellClicked($event)"
        (sortChanged)="lastEvent.set('onSortChanged')"
        (selectionChanged)="onSelectionChanged($event)"
        (cellValueChanged)="onCellValueChanged($event)"
        [cellSelection]="cellSelectionValue()"
        [rangeSelection]="rangeSelection()"
        [columnSelection]="columnSelection()"
        [editTrigger]="editTrigger()"
        [suppressKeyboardEdit]="suppressKeyboardEdit()"
        [suppressTypeToEdit]="suppressTypeToEdit()"
        [moveAfterEdit]="moveAfterEdit()"
        [commitOnBlur]="commitOnBlur()"
        [bodyContextMenu]="bodyContextMenu()"
        [showColumnButtonsOnHover]="buttonsOnHover()"
        [theme]="theme()"
        [columnPanel]="true"
      />
    </div>

    <div class="vs-event-log">
      Last event: <span style="color: var(--pte-text-color, #111)">{{ lastEvent() }}</span>
    </div>
  `,
  styles: [
    `
      :host { display: flex; flex-direction: column; height: 100%; gap: 12px; min-height: 0 }
      .vs-controls { display: flex; align-items: center; gap: 20px; flex-wrap: wrap }
      .vs-group { display: flex; align-items: center; gap: 14px; padding: 6px 12px; border: 1px solid var(--pte-frame-border-color, #ccc); border-radius: 8px }
      .vs-group-title { font-size: 12px; text-transform: uppercase; letter-spacing: 0.4px; color: #6b7280 }
      .vs-select { display: flex; align-items: center; gap: 6px; font-size: 13px }
      .vs-theme-picker { display: flex; align-items: center; gap: 8px }
      .vs-blurb { font-size: 12px; color: #6b7280; margin: 0 }
      .vs-event-log { font-size: 12px; color: #6b7280; font-family: monospace }
    `,
  ],
})
export class VisualStatesDemoComponent {
  readonly rows = buildRows(200);
  readonly themePresets = themePresets;

  readonly rowHover = signal(true);
  readonly columnHover = signal(true);
  readonly zebraRows = signal(true);
  readonly highlightActiveCell = signal(true);

  // Interaction gating (defaults preserve today's behavior).
  readonly cellSelection = signal<"true" | "false" | "text">("true");
  readonly rangeSelection = signal(true);
  readonly columnSelection = signal(true);
  readonly bodyMenu = signal<"default" | "native" | "custom" | "empty">("default");
  readonly editTrigger = signal<"doubleClick" | "singleClick" | "none">("doubleClick");
  readonly suppressKeyboardEdit = signal(false);
  readonly suppressTypeToEdit = signal(false);
  readonly moveAfterEdit = signal(true);
  readonly commitOnBlur = signal(true);

  // Conditional styling (getRowStyle + per-column cellStyle/cellClass).
  readonly conditionalStyling = signal(true);

  // Sort config: an initial sort (Salary desc) + a custom Department comparator (by a fixed order).
  // NOTE: initial sort seeds ONCE at first column setup, so toggling it needs a grid remount (key).
  readonly sortConfig = signal(true);

  // Event-callback readout: shows the most recent grid event (cellClicked / sortChanged / …).
  readonly lastEvent = signal<string>("—");

  // Header / column-menu options.
  readonly buttonsOnHover = signal(false);
  // Per-column flags demonstrated on specific columns: hide the menu (⋮) button on "Rating", and
  // disable the right-click column menu on "City" (its header falls back to the native menu).
  readonly hideRatingMenu = signal(true);
  readonly nativeCityMenu = signal(true);

  readonly themeId = signal(themePresets[0].id);
  readonly customColors = signal(false);

  readonly activePreset = computed(
    () => themePresets.find((t) => t.id === this.themeId()) ?? themePresets[0],
  );

  // Map the string control to the option's boolean | "text" value.
  readonly cellSelectionValue = computed<boolean | "text">(() =>
    this.cellSelection() === "text" ? "text" : this.cellSelection() === "true",
  );

  // Map the body-menu control onto bodyContextMenu's boolean | getter shape.
  readonly bodyContextMenu = computed<
    boolean | ((p: { ctx: BodyMenuContext; items: NgMenuItem[] }) => NgMenuItem[])
  >(() => {
    switch (this.bodyMenu()) {
      case "native": return false;                                    // browser's native menu
      case "empty": return () => [];                                  // grid owns it, shows nothing
      case "custom":                                                  // defaults + a custom item
        return ({ items }: { items: NgMenuItem[] }) => [
          ...items,
          { isSeparator: true },
          { id: "hello", label: "Say hello", onClick: () => window.alert("Hello from a custom item!") },
        ];
      default: return true;                                           // default grid menu
    }
  });

  readonly theme = computed<GridTheme | undefined>(() => {
    if (!this.customColors()) return undefined;
    const base = this.themeId() === "dark" ? themeDark : themeLight;
    return base.withParams(this.themeId() === "dark" ? CUSTOM_PARAMS_DARK : CUSTOM_PARAMS);
  });

  // getRowStyle: subtly dim inactive employees (active === "No").
  readonly getRowStyle = computed(() =>
    this.conditionalStyling()
      ? (p: RowClassParams) => ((p.data as PersonRow).active === "No" ? { opacity: "0.55" } : undefined)
      : undefined,
  );

  readonly columnDefs = computed<NgColDef[]>(() => [
    { colId: "id", key: "id", label: "ID", width: 80 },
    // Editable → the body context menu gains Cut / Paste (right-click a Name cell).
    { colId: "name", key: "name", label: "Name", width: 160, editable: true, filter: true },
    {
      colId: "department", key: "department", label: "Department", width: 140, filter: true,
      // Custom comparator: sort by a fixed department priority rather than alphabetically.
      comparator: this.sortConfig()
        ? (a: string, b: string) => DEPTS.indexOf(a) - DEPTS.indexOf(b)
        : undefined,
    },
    // columnContextMenu: false → right-clicking this header shows the browser's native menu.
    { colId: "city", key: "city", label: "City", width: 130, filter: true, columnContextMenu: !this.nativeCityMenu() },
    {
      colId: "salary", key: "salary", label: "Salary", width: 120, type: ColumnType.NUMBER,
      // Initial sort: Salary descending on first load.
      sort: this.sortConfig() ? "desc" : undefined,
      // cellStyle: color high salaries green, low ones muted (function of the cell value).
      cellStyle: this.conditionalStyling()
        ? (p: { value: number }) => ({ color: p.value >= 150_000 ? "#16a34a" : "#9ca3af", fontWeight: p.value >= 150_000 ? "600" : "400" })
        : undefined,
    },
    // showColumnMenu: false → the ⋮ button is hidden on this header (menu still via right-click).
    { colId: "rating", key: "rating", label: "Rating", width: 100, type: ColumnType.NUMBER, showColumnMenu: !this.hideRatingMenu() },
    { colId: "active", key: "active", label: "Active", width: 90 },
  ]);

  onCellClicked(p: GridEventCellClickedParams): void {
    this.lastEvent.set(`onCellClicked → row ${String(p.rowId)}, col "${String(p.colId)}" = ${JSON.stringify(p.value)}`);
  }

  onSelectionChanged(p: GridEventSelectionChangedParams): void {
    this.lastEvent.set(`onSelectionChanged → ${p.snapshot.kind}`);
  }

  onCellValueChanged(p: CellValueChangedParams): void {
    this.lastEvent.set(`onCellValueChanged → row ${String(p.rowId)}, col "${String(p.colId)}" = ${JSON.stringify(p.value)}`);
  }

  setCellSelection(ev: Event): void {
    this.cellSelection.set((ev.target as HTMLSelectElement).value as "true" | "false" | "text");
  }

  setEditTrigger(ev: Event): void {
    this.editTrigger.set((ev.target as HTMLSelectElement).value as "doubleClick" | "singleClick" | "none");
  }

  setBodyMenu(ev: Event): void {
    this.bodyMenu.set((ev.target as HTMLSelectElement).value as "default" | "native" | "custom" | "empty");
  }

  setThemeId(ev: Event): void {
    this.themeId.set((ev.target as HTMLSelectElement).value);
  }
}
